sudo: false
language: node_js
node_js:
- '0.12'
- '4'
- '5'
notifications:
  email:
    on_success: always
    on_failure: always
matrix:
  fast_finish: true
deploy:
  provider: npm
  api_key:
    secure: deowQmEb1PKVWN2A9tXSdyRaVO5tTd16oZqn7rc8VPid8o+JPy+2Iv4YnQPshXn1ToYbSpSndW0whhDPHON9hBYgdsNWIvUDEDtEx20ca+7NaafDdaY3cFWag+aGGs1OLak/u3JUSyspvzRjG0POi2WX5s8izW6RyIWT0cs6zxk=
  email: steven.jmiller@gmail.com
  on:
    repo: yargalot/AccessSniff
    branch: master
    tags: true
